#!/usr/bin/env bash

bundle="/usr/bin/env bundle"
ruby="/usr/bin/env ruby"

$bundle exec $ruby "bitstamp_cli.rb" $*

# simpler version without bundler:
#
# #!/usr/bin/env ruby
# require_relative 'bitstamp_cli'
