#!/usr/bin/env bash

bundle="/usr/bin/env bundle"
ruby="/usr/bin/env ruby"
dir=$(dirname $0)


BUNDLE_GEMFILE=$dir/Gemfile $bundle exec $ruby "$dir/bitstamp_cli.rb" $*

# simpler version without bundler:
#
# #!/usr/bin/env ruby
# require_relative 'bitstamp_cli'
